<h2>Alfabet Fonetik Penegak Hukum</h2>
                <div class="ten-codes-two-columns">
                    <table>
                        <thead>
                            <tr>
                                <th>Letter</th>
                                <th>Word</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr><td>A</td><td>ADAM</td></tr>
                            <tr><td>B</td><td>BRAVO</td></tr>
                            <tr><td>C</td><td>CHARLIE</td></tr>
                            <tr><td>D</td><td>DELTA</td></tr>
                            <tr><td>E</td><td>EDWARD</td></tr>
                            <tr><td>F</td><td>FRANK</td></tr>
                            <tr><td>G</td><td>GEORGE</td></tr>
                            <tr><td>H</td><td>HENRY</td></tr>
                            <tr><td>I</td><td>IDA</td></tr>
                            <tr><td>J</td><td>JOHN</td></tr>
                            <tr><td>K</td><td>KING</td></tr>
                            <tr><td>L</td><td>LINCOLN</td></tr>
                            <tr><td>M</td><td>MARY</td></tr>
                        </tbody>
                    </table>
                    <table>
                        <thead>
                            <tr>
                                <th>Letter</th>
                                <th>Word</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr><td>N</td><td>NORA</td></tr>
                            <tr><td>O</td><td>OCEAN</td></tr>
                            <tr><td>P</td><td>PAUL</td></tr>
                            <tr><td>Q</td><td>QUEEN</td></tr>
                            <tr><td>R</td><td>ROBERT</td></tr>
                            <tr><td>S</td><td>SAM</td></tr>
                            <tr><td>T</td><td>TOM</td></tr>
                            <tr><td>U</td><td>UNION</td></tr>
                            <tr><td>V</td><td>VICTOR</td></tr>
                            <tr><td>W</td><td>WILLIAM</td></tr>
                            <tr><td>X</td><td>X-RAY</td></tr>
                            <tr><td>Y</td><td>YOUNG</td></tr>
                            <tr><td>Z</td><td>ZEBRA</td></tr>
                        </tbody>
                    </table>
                </div>